AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ClusterName:
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16

  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.1/16

  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      CapacityProviders:
        - FARGATE
        ClusterName: !Ref ClusterName
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 100
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
